name: Docker Build And Push

on:
    push:
        branches:
            - production


jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker Image
              run: docker build -t "${{ secrets.IMAGE_NAME }}":latest ./frontend/

            - name: Push Docker Image
              run: docker push "${{ secrets.IMAGE_NAME }}":latest

            - name: Wait For 20s
              run: sleep 20

            - name: Trigger Deployment Webhook
              run: curl "${{ secrets.DEPLOYMENT_WEBHOOK }}"